### PR TITLE
fix(TemplateLibrary): Upload template Working

### LINKED ISSUE #35: "Upload your template" button not working
# Bug Report 🐛

`Upload your template` button not working.

## Expected Behavior

Clicking on the `Upload your template` button and selecting a template should render that particular template (`.cta`) file on the document.

## Current Behavior

Clicking on the `Upload your template` button and selecting a template does nothing.

## Steps to Reproduce

1. You can download a `.cta` file for any template from [here](https://templates.accordproject.org/).
2. Get the add-in working and click on the `Upload your template button
3. Select that downloaded `.cta` file.
4. That template file should get rendered on the document but nothing happens.

### Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version 88.0.4324.182 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by d-e-v-esh**
Signed-off-by: d-e-v-esh <59534570+d-e-v-esh@users.noreply.github.com>

# Closes #35 

Clicking on the `Upload your template` button and selecting a template should render that particular template (`.cta`) file but that was not working because => `setup` function (the function that is responsible to render templates on the document) was being called with incorrect values inside `uploadYourTemplate` function

### Changes

- <ONE> Calling the `setup` function with the correct values fixes this bug.
- Beforehand it was being called with the  `ciceromark` (the JSON object) and `templateIdentifier`.
- It should be called with `ciceromark` and the uploaded `template` file.

### Screenshots or Video

aH2YeC9XQf

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [x] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [x] Merging to `master` from `fork:branchname`
- [x] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [x] Appropriate labels, alt text, and instructions

### CODE REVIEW

**Comment by Aniruddha-Shriwant** [comment]
https://www.loom.com/share/09d30f2e683a4108ad2da2b0e68ffaa8
Can you see this video I got that error after doing the exact same change as you did...
Don't know maybe this problem would be with my Add-in :) 
Edit: After Restarting too the Add-in was not able to import the template

File: src/components/TemplateLibrary/index.js [hunk 1]
```diff
@@ -36,7 +36,7 @@ const LibraryComponent = () => {
       const template = await Template.fromArchive(fileUploaded);
       const templateIdentifier = template.getIdentifier();
```
Comment (Aniruddha-Shriwant) [inline src/components/TemplateLibrary/index.js]: If the issue I mentioned [here](https://github.com/accordproject/cicero-word-add-in/pull/36#issuecomment-812546885) is only with me,
then you may remove `const templateIdentifier = template.getIdentifier();` as the linter test won't pass

Comment (d-e-v-esh) [reply src/components/TemplateLibrary/index.js]: Oh ya, I totally forgot about that. I'll create the new PR in sometime...

**Comment by d-e-v-esh** [comment]
> https://www.loom.com/share/09d30f2e683a4108ad2da2b0e68ffaa8
> Can you see this video I got that error after doing the exact same change as you did...
> Don't know maybe this problem would be with my Add-in :)
> Edit: After Restarting too the Add-in was not able to import the template

Did you make sure that the plugin fully recompiled and the changes were saved because sometimes it takes a little longer for it to be ready...

**Review by algomaster99 — APPROVED** [review]
Thanks @d-e-v-esh !

Just a small piece of advice. Do not submit a pull request even from your fork's master branch. 

1. https://blog.jasonmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/
2. Can lead to lot of rebasing if lot of people are contributing.

**Comment by d-e-v-esh** [comment]
@algomaster99 Yes, I'll remember that. Thank you.
