### PR TITLE
fix: Multiple template handling

### LINKED ISSUE #25: Handle multiple templates with same identifier
We need to restrict user to upload templates with unique identifier. This will help us re-attaching the listeners more efficiently.

To explain this more briefly, I will elaborate on how the listeners get attached in the first place.

1. Whenever a template is added for the first time, the template identifier is stored, as [`CustomXMPart`](https://docs.microsoft.com/en-us/javascript/api/office/office.customxmlpart?view=common-js), in the document which looks something like this:
    ```xml
    <?xml version="1.0" encoding="utf-8" ?>
    <templates xmlns="https://accordproject.org/">
      <template xmlns="acceptance-of-delivery@0.14.0" />
      ...
    </templates>
    ```
    > If `acceptance-of-delivery@0.14.0` is added two times, the xml **will not** show two occurrences of `<template xmlns="acceptance-of-delivery@0.14.0" />`. (This is purposely added because I thought it may unnecessarily populate the XML)

2. When the Add-in is opened, it iterates over this `XML` and fetches the corresponding compiled archives and list down the variables they contain.
    ```js
    ["Shipper1", "Receiver1", "Deliverable1", "Receiver2", "Shipper2", "Deliverable2", "Receiver3", "BusinessDays1", "Deliverable3", "Shipper3", "Deliverable4", "Deliverable5", "Shipper4", "Attachment1"]
    ```

3.  A function then iterates over this list and add listener to the content control **if** it is also present in the above list.

The problem here is that we don't have a way to enumerate the times a template exists in the document. But I suggest three approaches for this:

1. Remove the check for uniqueness in the XML.
2. Generate the XML something like this:
    ```xml
    <?xml version="1.0" encoding="utf-8" ?>
    <templates xmlns="https://accordproject.org/">
      <template xmlns="acceptance-of-delivery@0.14.0">3</template>
      ...
    </templates>
    ```
    > not sure if one will be able to query the XML properly.
3. Add a function to restrict user to add templates with unique identifier.

### PR DESCRIPTION
**Pull request by K-Kumar-01**
Signed-off-by: K-Kumar-01 <59891164+K-Kumar-01@users.noreply.github.com>

# Closes #25 <CORRESPONDING ISSUE NUMBER>

Currently, multiple templates with the same identifier can be inserted. We need to ensure that we cannot insert more than one template with the same identifier. The PR aims at that. Now inserting more than one template with the same template won't be possible.

### Changes

- <ONE> Checks if the identifier is present in the `customXML` part.
- <TWO> If present, `console.info(Template present)` else insert the template.

### Flags

- <ONE> Currently if the template is already present, so there is only a `console.info()`. This may cause users to think that the add-in is not working. We can show a dialog here(I have made some comments on that portion depicting how it can be made).

### Screenshots or Video

Screenshot (50)
Screenshot (49)

I tried recording but the debugger was not being shown in the video. Hence, I have shared the screenshots representing the same

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [x] Extend the documentation, if necessary
- [x] Merging to `master` from `fork:branchname`
- [ ] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

### CODE REVIEW

**Comment by K-Kumar-01** [comment]
@algomaster99 @irmerk @DianaLease 
Requesting your reviews.

EDIT: Also, I had an alternative approach where instead of using the XML queries, we can store the template identifers in a state which are already present in the document and iterate over them. IMO, it will be faster as compared to this one though it needs discussion.

File: src/components/TemplateLibrary/index.js [hunk 1]
```diff
@@ -177,8 +177,37 @@ const LibraryComponent = () => {
...
+      if (result.status === Office.AsyncResultStatus.Succeeded) {
+        if (result.value.length === 0) {
+          setup(ciceroMark, template);
+          saveTemplateToXml(templateIdentifier);
+        }
+        else {
+          const customXmlPart = result.value[0];
+          customXmlPart.getNodesAsync('*/*', result => {
+            if (result.status === Office.AsyncResultStatus.Succeeded) {
+              let f=1;
```
Comment (algomaster99) [inline src/components/TemplateLibrary/index.js]: Be more descriptive. Use good variable names such as "identifierExists".

File: src/components/TemplateLibrary/index.js [hunk 2]
```diff
@@ -177,8 +177,37 @@ const LibraryComponent = () => {
...
+                    f=0;
+                  }
+                }
+              }
+              if(f){
+                setup(ciceroMark, template);
+                saveTemplateToXml(templateIdentifier);
+              }else{
+                console.info('Already present template');
+                // Office.context.ui.displayDialogAsync(`${window.location.origin}/bad-file.html`, { width: 30, height: 8 });
```
Comment (algomaster99) [inline src/components/TemplateLibrary/index.js]: I remember I did that initially. But I think it would be great if we can show toasts inside add-in. Just a suggestion. Let me know what you think.

File: src/components/TemplateLibrary/index.js [hunk 3]
```diff
@@ -177,8 +177,37 @@ const LibraryComponent = () => {
     const template = await Template.fromUrl(templateIndex.ciceroUrl);
     const ciceroMark = templateToCiceroMark(template);
     const templateIdentifier = template.getIdentifier();
-    setup(ciceroMark, template);
-    saveTemplateToXml(templateIdentifier);
+    Office.context.document.customXmlParts.getByNamespaceAsync(CUSTOM_XML_NAMESPACE, result => {
```
Comment (algomaster99) [inline src/components/TemplateLibrary/index.js]: I think it would be a better idea to combine this with `saveTemplateToXml` as these callbacks are unnecessarily making the codebase huge.

Your code can be [put somewhere here instead](https://github.com/accordproject/cicero-word-add-in/pull/44/files#diff-4fea1789b5aec0804243466b09cef28905138a856013ec86e70e7f824035affaR221).

**Review by algomaster99 — CHANGES_REQUESTED** [review]
@K-Kumar-01 good work :tada: I haven't tested the changes as I don't have a Windows PC but the code looks fine to me.

Just run it through eslint once and then push the changes.

P.S. Another good idea would be to integrate pre-commit hooks for the project. :)

File: src/components/TemplateLibrary/index.js (hunk 1 above)
Comment (K-Kumar-01) [reply src/components/TemplateLibrary/index.js]: @algomaster99 
I will keep this in mind.

File: src/components/TemplateLibrary/index.js (hunk 2 above)
Comment (K-Kumar-01) [reply src/components/TemplateLibrary/index.js]: @algomaster99 
I searched how to implement toasts but couldn't find anything suitable.
As for toasts inside add-in, can we have a notifications bar where we show all the notifications like listeners attached and other necessary details?

File: src/components/TemplateLibrary/index.js (hunk 3 above)
Comment (K-Kumar-01) [reply src/components/TemplateLibrary/index.js]: @algomaster99 
Yeah, this seems to be better. I will implement these ASAP.

**Comment by K-Kumar-01** [comment]
> P.S. Another good idea would be to integrate pre-commit hooks for the project. :)

@algomaster99 
Should I open an issue regarding the same?

File: src/components/TemplateLibrary/index.js (hunk 2 above)
Comment (algomaster99) [reply src/components/TemplateLibrary/index.js]: You can implement toasts inside add-in.

**Comment by algomaster99** [comment]
> Should I open an issue regarding the same?

Yes! Go ahead.

File: src/components/TemplateLibrary/index.js (hunk 2 above)
Comment (K-Kumar-01) [reply src/components/TemplateLibrary/index.js]: @algomaster99 
I didn't get this part. Is there any reference which I can look up to?

**Comment by K-Kumar-01** [comment]
@algomaster99 
I have updated my PR.
Currently, the toast functionality is not implemented in this PR. I think we can see this as a separate issue as toast need to be used in many places besides here. What do you think about this?

File: src/components/TemplateLibrary/index.js (hunk 2 above)
Comment (algomaster99) [reply src/components/TemplateLibrary/index.js]: https://toasted-notes.netlify.app/

You can implement toasts like here on this link.

**Comment by K-Kumar-01** [comment]
> > Should I open an issue regarding the same?
> 
> Yes! Go ahead.

@algomaster99 
I have created an issue for this. Please see if there the description is suitable or not.

File: src/components/TemplateLibrary/index.js (hunk 2 above)
Comment (K-Kumar-01) [reply src/components/TemplateLibrary/index.js]: Screenshot (51)
@algomaster99 
Is this fine? The styling will be changed accordingly to make it look like error

**Comment by K-Kumar-01** [comment]
@algomaster99 
I have updated my code to include the toast in the add-in.

Screenshot (54)

Let me know if any change is required

File: src/components/TemplateLibrary/index.js [hunk 4]
```diff
@@ -200,24 +206,33 @@ const LibraryComponent = () => {
...
+                  }
                 }
               }
-              newXml += `<template xmlns="${templateIdentifier}" />`;
-              newXml += '</templates>';
-              Office.context.document.customXmlParts.getByNamespaceAsync(CUSTOM_XML_NAMESPACE, res => {
-                if (res.status === Office.AsyncResultStatus.Succeeded) {
-                  for (let index=0; index<res.value.length; ++index) {
-                    res.value[index].deleteAsync();
+              if(!identifierExists){
```
Comment (algomaster99) [inline src/components/TemplateLibrary/index.js:218]: In a separate PR, add rules for [block-spacing](https://eslint.org/docs/rules/space-before-blocks) so that this translates to `if (!identifierExists) {` (notice the spaces).

File: src/components/TemplateLibrary/index.js [hunk 5]
```diff
@@ -200,24 +206,33 @@ const LibraryComponent = () => {
...
+                    for (let index=0; index<res.value.length; ++index) {
+                      res.value[index].deleteAsync();
+                    }
                   }
-                }
-              });
-              Office.context.document.customXmlParts.addAsync(newXml);
+                });
+                Office.context.document.customXmlParts.addAsync(newXml);
+              }else{
```
Comment (algomaster99) [inline src/components/TemplateLibrary/index.js:230]: Same goes for this block.

File: package.json [hunk 6]
```diff
@@ -33,6 +33,7 @@
     "prop-types": "^15.7.2",
     "react": "^16.8.2",
     "react-dom": "^16.10.2",
+    "react-toast-notifications": "^2.4.3",
```
Comment (algomaster99) [inline package.json]: @irmerk do we have a component for toasts? Or are we using something else for toast in any other project?

Regardless, I think we should use [this package](https://www.npmjs.com/package/react-semantic-toasts) as we are already using semantic-ui so makes more sense to be consistent with styling.

**Review by algomaster99 — CHANGES_REQUESTED** [review]

File: src/components/TemplateLibrary/index.js (hunk 4 above)
Comment (Aniruddha-Shriwant) [reply src/components/TemplateLibrary/index.js:218]: @algomaster99 and/or @K-Kumar-01, May I work on this?

Comment (algomaster99) [reply src/components/TemplateLibrary/index.js:218]: Go for it!

Comment (Aniruddha-Shriwant) [reply src/components/TemplateLibrary/index.js:218]: Sure thanks!

File: package.json (hunk 6 above)
Comment (K-Kumar-01) [reply package.json]: @algomaster99 
Should I go with the package you mentioned?

Comment (algomaster99) [reply package.json]: Yes, go ahead!

**Comment by K-Kumar-01** [comment]
@algomaster99 
I have replaced the toast package.
Screenshot (55)
Let me know if there are any changes required.

**Comment by K-Kumar-01** [comment]
@algomaster99 
Any updates on this one?

File: src/components/TemplateLibrary/index.js [hunk 7]
```diff
@@ -200,24 +203,44 @@ const LibraryComponent = () => {
...
+                  {
+                    title: 'Duplicate template',
+                    description: <p>Template cannot be inserted as it is already present in the document.</p>,
+                    type: 'error',
+                    time: 5000,
+                    animation: 'fly down',
+                  },
+                  () => console.log('toast closed'),
+                  () => console.log('toast clicked'),
+                  () => console.log('toast dismissed')
```
Comment (algomaster99) [inline src/components/TemplateLibrary/index.js]: These `console` statements are not required as it doesn't matter to us how the user interacts with the toast. You can remove them.

File: src/components/TemplateLibrary/index.js [hunk 8]
```diff
@@ -200,24 +203,44 @@ const LibraryComponent = () => {
...
           customXmlPart.getNodesAsync('*/*', result => {
             if (result.status === Office.AsyncResultStatus.Succeeded) {
+              let identifierExists = false;
               let newXml = XML_HEADER + `<templates xmlns="${CUSTOM_XML_NAMESPACE}">`;
               if (result.value.length > 0) {
                 for (let node=0; node < result.value.length; ++node) {
                   if (result.value[node].namespaceUri !== templateIdentifier) {
                     newXml += `<template xmlns="${result.value[node].namespaceUri}" />`;
                   }
+                  if(result.value[node].namespaceUri === templateIdentifier){
```
Comment (algomaster99) [inline src/components/TemplateLibrary/index.js]: Just use an `else` block here.

**Review by algomaster99 — CHANGES_REQUESTED** [review]
Sorry for the delay in review. Just some small changes and we are good to go.

**Comment by K-Kumar-01** [comment]
@algomaster99 
I have updated my PR and made the changes. Let me know if there are any more changes required.

**Review by algomaster99 — APPROVED** [review]
Nice work! The code looks good to me. I will just test this once on a Windows laptop and will merge it.
